### ISSUE TITLE
Adventure Planets in Space Stage get overwritten

### ISSUE THREAD

**Issue by MarsIandare** [VanillaCold/Spore-CommunityPlanetExpedition#12]
Like the title suggests, when entering an adventure the terrain gets replaced and sometimes make it impossible to finish.
All props, creatures, buildings, ect... they all seem to be where they should be though.

This issue might already have been solved as i just built my own version of the source code from github and i don't know if it's up to date or not.

**Comment by VanillaCold** [comment]
The main branch on the source code is actually using an older system for replacing planet terrain.
The `improve-homeworlds` branch uses a better system that actually cannot overwrite adventures at all, since it's instead using vanilla Spore's homeworld system.

**Comment by MarsIandare** [comment]
Aha, well thanks for explaining.
